name: Primary Verification Workflow

on:
  push:
    branches: 
      - main
      - master
      - develop
  workflow_dispatch:  # Added manual trigger

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          npm ci 
          cd country-explorer
          npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: country-explorer
          start: npm run dev
          wait-on: 'http://localhost:5173'
          spec: |
            cypress/e2e/auth_flow.cy.js
            cypress/e2e/main_flow.cy.js
          
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          cd country-explorer-backend
          npm ci
          
      - name: Run API tests
        run: |
          cd country-explorer-backend
          npm test -- --testPathPattern=auth.test.js